// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR60MWjTFaDpgSyVkC_IY-k4d_qSL4RlY',
    appId: '1:3679278244:web:fa9b796a58d6c9d6f24231',
    messagingSenderId: '3679278244',
    projectId: 'indah-fb',
    authDomain: 'indah-fb.firebaseapp.com',
    storageBucket: 'indah-fb.appspot.com',
    measurementId: 'G-4B36B8VZML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOkn8_13XMtzcz8JIa2erc3Fnov3Xd1RQ',
    appId: '1:3679278244:android:31eb5b5dd70067a1f24231',
    messagingSenderId: '3679278244',
    projectId: 'indah-fb',
    storageBucket: 'indah-fb.appspot.com',
  );
}
